modLoader="javafml"
loaderVersion="[24,)"
#issueTrackerURL="https://github.com/CreativeMD/CMDCam/issues"
logoFile="cmdcam.png"

[[mods]]
	modId="cmdcam"
	version="1.5.0"
	displayName="CMDCam"
	side="CLIENT"
	displayURL="https://minecraft.curseforge.com/projects/cmdcam"
	authors="CreativeMD"
	description='''
	Create camera paths.
	'''